/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/airplane/car.glb 
Author: CG Boost (https://sketchfab.com/zreinhardt)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flying-trabant-final-takeoff-44de9112ce564d35be97a06c302a2fe3
Title: Flying Trabant (Final Takeoff)
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/car.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
        <mesh geometry={nodes.car_small_parts_low_small_parts_0.geometry} material={materials.small_parts} />
        <mesh geometry={nodes.car_small_parts_low_small_parts_0_1.geometry} material={materials.small_parts} />
        <mesh geometry={nodes.car_small_parts_low_small_parts_0_2.geometry} material={materials.small_parts} />
        <mesh geometry={nodes.car_small_parts_low_small_parts_0_3.geometry} material={materials.small_parts} />
        <mesh geometry={nodes.car_small_parts_low_small_parts_0_4.geometry} material={materials.small_parts} />
        <mesh geometry={nodes.car_small_parts_low_small_parts_0_5.geometry} material={materials.small_parts} />
        <mesh geometry={nodes.car_small_parts_low_small_parts_0_6.geometry} material={materials.small_parts} />
        <mesh geometry={nodes.car_small_parts_low_small_parts_0_7.geometry} material={materials.small_parts} />
      </group>
      <mesh geometry={nodes.car_windows_windows_0.geometry} material={materials.windows} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.car_big_parts_low_big_parts_0.geometry} material={materials.big_parts} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
      <mesh geometry={nodes.car_fire_fire_0.geometry} material={materials.fire} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/car.glb')
